[CI] Update Conan version
1.55.0 has issues with several more modern recipies leading to fun such as:

ERROR: ncurses/6.2: Error in build() method, line 195
    self._patch_sources()
while calling '_patch_sources', line 173
    tools.patch(**patch)
TypeError: patch() got an unexpected keyword argument 'patch_type'

Later versions of Conan 1.x seem to follow the pattern in 2.x, whereby
build_dependencies are not collected if published pre-built artifacts
are used for the main project dependencies. As such, we need to move
TOML++ into the main dependencies section.

Signed-off-by: Tom Cowland <tom@foundry.com>